### ISSUE TITLE
Does this work with Flutter Web?

### ISSUE THREAD

**Issue by lazyweb3** [wakumo/flutter-wallet-connect-v2#10]
I'm working on a flutter app(android/ios/web), I want to use this package but quite unsure if it works fine with web as well.
I could not find any place where I could communicate so creating this issue.

Thank you

**Comment by ludowkm** [comment]
Hello @lazyweb3 , this library is currently support for android and ios, not yet for web version.
I have no plan to make support for web so just welcome others to create PRs.

**Comment by lazyweb3** [comment]
got it, thank you for clarifying @ludowkm 🚀
