### ISSUE TITLE
Got TimeoutCancellationException exception when client.pair(wcuri)

### ISSUE THREAD

**Issue by mmMrz** [wakumo/flutter-wallet-connect-v2#14]
await _client.init(projectId: "my_project_id", appMetadata: metadata);
    await _client.connect();
    await _client.pair(uri: wcUri);

I always got the TimeoutCancellationException  from kotlin. anyone has the same issue?

**Comment by ludowkm** [comment]
Did you meet this issue with the example on the library ?
Otherwise then you can follow exact with the implementation on example
