### ISSUE TITLE
How to connect with DApp (MetaMask, ....)

### ISSUE THREAD

**Issue by nqhhdev** [wakumo/flutter-wallet-connect-v2#15]
OS: IOS, Android
Device: Mobile
*Precondition:

Connect with MetaMask

*Data test: Account

*Reproduce Step:
1, Use `createPair` to send request connect to MetaMask

```
final uri = await _walletConnectV2Plugin
            .createPair(namespaces: {
          'eip155': ProposalNamespace(chains: [
            'eip155:1'
          ], methods: [
            "eth_signTransaction",
          ], events: ["connect", "disconnect"])
        });
        launchUrlString(
          uri!,
          mode: LaunchMode.externalApplication,
        );
```
2, Redirect to MetaMask app but can't show popup request

Actual:
Don't show popup to confirm sign connect

Expected:
How to work for metaMask

**Comment by ludowkm** [comment]
hello @nqhhdev , you can run the example to see and follow it to have connection with the wallet
if there is any problem, leave more comment here

**Comment by nqhhdev** [comment]
> hello @nqhhdev , you can run the example to see and follow it to have connection with the wallet if there is any problem, leave more comment here

Thanks for your feedback, I saw Walletconnect docs, it does not support MM V2. Waittt for WC ....

**Comment by ludowkm** [comment]
Yes, Metamask is still not yet support WC v2.
But there are many wallets integrating WC v2, for example [Avacus](https://avacus.cc), you can try with that to continue your integration.
So i will close this issue, if there is anything else, feel free to re-open.
