### ISSUE TITLE
Doubt for chain switching.

### ISSUE THREAD

**Issue by kamalpreet-singh01** [wakumo/flutter-wallet-connect-v2#19]
By default my remix is connected to chainID: 42161 but I wanted to connect it with Goerli(ChainID: 5). When I try to switch network on remix, it shows me no implementation for `wallet_addEthereumChain` method(when I'm using example inside this repo).
I'm unable to understand how it handles the switching of chains? Any snippet/ function for this?

**Comment by ludowkm** [comment]
Hi @kamalpreet-singh01 , along with `personal_sign`, `eth_sendTransaction`,.... you just need to add `wallet_addEthereumChain` on switch case to handle this request

**Comment by ludowkm** [comment]
This must be our implementation and it's not issue of this library so i close this issue, feel free to re-open if there is anything else.
