### ISSUE TITLE
Reconnect problem

### ISSUE THREAD

**Issue by JCZuu** [wakumo/flutter-wallet-connect-v2#2]
How to reconnect to WalletConnect V2 when the app cold start？
Do you have any good ideas？

**Comment by JCZuu** [comment]
哈罗，我是祝国庆，我已经收到你的邮件，谢谢你还记得我，我会在最快时间内阅读邮件并回复

**Comment by ludowkm** [comment]
If you follow the example but does not keep stable connection, let's re-open the issue.
Otherwise, i will close this current issue as we can keep stable connection, take a look again on Example project or try our Avacus wallet @ https://avacus.cc

**Comment by JCZuu** [comment]
哈罗，我是祝国庆，我已经收到你的邮件，谢谢你还记得我，我会在最快时间内阅读邮件并回复
