### ISSUE TITLE
Namespaces support? 

### ISSUE THREAD

**Issue by rhamnett** [wakumo/flutter-wallet-connect-v2#24]
Hello, thanks for your continued contribution on this project. I am wondering how to support namespaces as per this document https://docs.walletconnect.com/web3wallet/namespaces

https://docs.walletconnect.com/web3wallet/wallet-usage#namespace-builder

There appears to be a deadline of Nov 27th, any information or documentation would be greatly appreciated.

Rich

**Comment by ludowkm** [comment]
Hello @rhamnett , the library is already supported the namespaces, from proposal, you can get required and optional namespaces to handle and send response to that proposal about session approval/rejection.
You can take a look at the simple example https://github.com/wakumo/flutter-wallet-connect-v2/blob/main/example/lib/main.dart#L130

**Comment by rhamnett** [comment]
Hello thanks for the reply, I ended up implementing with some null checks and managed to get it to work.

```
            final List<String> chainList = [];
            // chainList.addAll(proposal.namespaces['eip155']!
            //     .chains!); // This line might throw the null error
            // // if (proposal.optionalNamespaces?['eip155']?.chains != null) {
            // //   chainList.addAll(proposal.optionalNamespaces!['eip155']!.chains!);
            // // }
            // if (proposal.namespaces['eip155'] != null && proposal.namespaces['eip155']!.chains != null) {
            //   chainList.addAll(proposal.namespaces['eip155']!.chains!);
            // }

            if (proposal.namespaces['eip155']?.chains != null) {
              chainList.addAll(proposal.namespaces['eip155']!.chains!);
            }

            // Check and add chains from optionalNamespaces['eip155'] if not null
            if (proposal.optionalNamespaces?['eip155']?.chains != null) {
              chainList.addAll(proposal.optionalNamespaces!['eip155']!.chains!);
            }
```
