### ISSUE TITLE
Doubt about connections

### ISSUE THREAD

**Issue by luizvnegrini** [wakumo/flutter-wallet-connect-v2#3]
The doubt is very simple, this package connects only with Eth? If no, how to connect with Btc and the others?

**Comment by ludowkm** [comment]
Hey @luizvnegrini , i made fast example app so i included one test network only for testing purpose.
If you are looking for connection for multiple chains, please take a look at https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-25.md and https://github.com/wakumo/flutter-wallet-connect-v2/blob/main/example/lib/main.dart#L82
Just adding your network support and handle for proposal request, your app will support all chains

**Comment by luizvnegrini** [comment]
@ludowkm thanks!!
