### ISSUE TITLE
Cannot pair uri

### ISSUE THREAD

**Issue by luannv1203** [wakumo/flutter-wallet-connect-v2#5]
![image](https://user-images.githubusercontent.com/43994963/222873922-910016e3-536f-4c1e-865b-445ed35f2c7b.png
Can you explain this error to me?
I try run example

**Comment by ludowkm** [comment]
hello @luannv1203 , are you trying to create pair uri from example and use the example to do pair with that uri ?

**Comment by ludowkm** [comment]
Hey @luannv1203 , let's use the example first. If the issue is still happen on your side, feel free to re-open the issue. Thank you!
